### ISSUE TITLE
컨트리뷰선 가이드

### ISSUE THREAD

**Issue by naverunion-staff** [naverunion/naverunion.github.io#27]

**Comment by naverunion-staff** [comment]
조합원 비조합원를 넘어 세상 누구나 세상을 빠꿀 네이버 노동조합이 써나갈 코드를 함께 쓰기 편하게 하기 위한 가이드 작성- 깃허브 위키에 작성(?)

**Comment by diginori** [comment]
https://github.com/naverunion/naverunion.github.io/wiki 에 작성
